first_name = input("Enter first name: ")
last_name = input("Enter last name: ")
dob = input("Date of Birth: ")
email_address = input("Email Address: ")
zip_code = input("Zip Code: ")
city = input("City: ")
state = input("State: ")
race = input("Race (Optional): ")
age = input("Age: ")
sex = input("Sex: ")


print(first_name)
print(last_name)
print(dob)
print(email_address)
print(zip_code)
print(city)
print(state)
print(race)
print(age)
print(sex)
